import type { Property, Profile } from "@/lib/types";

// Fallback seed used when Supabase env is not configured.
// Mirrors supabase/migrations/0002_seed.sql so the demo works without Supabase.

export const DEMO_OWNER: Profile = {
  id: "11111111-1111-1111-1111-111111111111",
  role: "asesor",
  full_name: "Rafael Oviedo",
  phone: "+58 414-1234567",
  avatar_url: null,
  bio: "Asesor inmobiliario en Llave, builder del Platanus Build Night ft. Anthropic. Especialista en Caracas — hablamos por DM cuando quieras.",
  city: "Caracas",
  rating_avg: 5.0,
  rating_count: 1,
  trust_score: 950,
};

const now = new Date().toISOString();
const owner = DEMO_OWNER.id;

function p(over: Partial<Property> & { title: string; price_usd: number; city: string; type: Property["type"]; rooms: number; bathrooms: number; cover_url: string }): Property {
  return {
    id: crypto.randomUUID(),
    owner_id: owner,
    description: "",
    address: "",
    state: "",
    country: "Venezuela",
    lat: null,
    lng: null,
    no_months_upfront: true,
    deposit_months: 1,
    area_m2: null,
    parking_spots: 0,
    amenities: [],
    rules: [],
    gallery_urls: [over.cover_url],
    spline_scene_url: null,
    tour_3d_url: null,
    splat_url: null,
    status: "disponible",
    created_at: now,
    ...over,
  } as Property;
}

export const DEMO_PROPERTIES: Property[] = [
  p({
    title: "Llave: Apartamento luminoso en Las Mercedes",
    description: "Apartamento de 2 habitaciones con vista a la ciudad. Edificio con seguridad 24/7, planta eléctrica y agua continua. Ideal para profesionales jóvenes o pareja.",
    type: "apartamento",
    address: "Av. Principal de Las Mercedes",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4806,
    lng: -66.8569,
    price_usd: 280,
    rooms: 2,
    bathrooms: 2,
    area_m2: 85,
    parking_spots: 1,
    amenities: ["planta electrica", "agua 24/7", "seguridad", "ascensor", "balcón"],
    rules: ["no mascotas grandes", "no fiestas"],
    cover_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
    gallery_urls: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200",
    ],
    // public Gaussian Splat demo so the 3D walkthrough feature is testable
    splat_url: "https://huggingface.co/cakewalk/splat-data/resolve/main/nike.splat",
  }),
  p({
    title: "Llave: Casa familiar en El Hatillo",
    description: "Casa de 3 habitaciones con jardín, garage para 2 carros y zona BBQ. Urbanización cerrada con vigilancia.",
    type: "casa",
    address: "Calle La Paz",
    city: "El Hatillo",
    state: "Miranda",
    lat: 10.4231,
    lng: -66.8267,
    price_usd: 450,
    rooms: 3,
    bathrooms: 3,
    area_m2: 180,
    parking_spots: 2,
    amenities: ["jardín", "garage doble", "zona BBQ", "seguridad", "tanque de agua", "planta electrica"],
    rules: ["cuidar jardín", "no fumar interior"],
    cover_url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
    gallery_urls: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200",
    ],
  }),
  p({
    title: "Llave: Estudio amoblado en Chacao",
    description: "Estudio totalmente amoblado, ideal para estudiantes o profesionales. Cerca del metro.",
    type: "apartamento",
    address: "Av. Francisco de Miranda",
    city: "Chacao",
    state: "Distrito Capital",
    lat: 10.496,
    lng: -66.8541,
    price_usd: 200,
    deposit_months: 0.5,
    rooms: 1,
    bathrooms: 1,
    area_m2: 35,
    amenities: ["amoblado", "agua 24/7", "wifi incluido", "cerca metro"],
    rules: ["no mascotas", "max 2 personas"],
    cover_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
    gallery_urls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200",
    ],
  }),
  p({
    title: "Llave: Apartamento moderno en Maracaibo Norte",
    description: "2 habitaciones con aire central. Piscina y gimnasio en el edificio.",
    type: "apartamento",
    address: "Av. 5 de Julio",
    city: "Maracaibo",
    state: "Zulia",
    lat: 10.6669,
    lng: -71.6122,
    price_usd: 250,
    rooms: 2,
    bathrooms: 2,
    area_m2: 78,
    parking_spots: 1,
    amenities: ["aire acondicionado", "piscina", "gimnasio", "seguridad", "planta electrica"],
    cover_url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
  }),
  p({
    title: "Llave: Casa colonial en Valencia centro",
    description: "Casa colonial restaurada de 4 habitaciones con patio interno.",
    type: "casa",
    address: "Av. Bolívar Norte",
    city: "Valencia",
    state: "Carabobo",
    lat: 10.162,
    lng: -68.0077,
    price_usd: 380,
    rooms: 4,
    bathrooms: 3,
    area_m2: 220,
    parking_spots: 2,
    amenities: ["patio interno", "techos altos", "garage", "planta electrica", "tanque"],
    cover_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
  }),
  p({
    title: "Llave: Local comercial en Sabana Grande",
    description: "Local de 80m² en planta baja, alto tránsito peatonal.",
    type: "local",
    address: "Bulevar de Sabana Grande",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4942,
    lng: -66.8767,
    price_usd: 600,
    deposit_months: 2,
    rooms: 0,
    bathrooms: 1,
    area_m2: 80,
    amenities: ["alto tránsito", "vitrina", "baño privado", "aire acondicionado"],
    cover_url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200",
  }),
  p({
    title: "Llave: Penthouse con terraza en Altamira",
    description: "Penthouse de 3 habitaciones con terraza panorámica de 60m². Jacuzzi exterior, vista al Ávila.",
    type: "apartamento",
    address: "Av. Luis Roche, Altamira",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4977,
    lng: -66.8487,
    price_usd: 850,
    rooms: 3,
    bathrooms: 3,
    area_m2: 220,
    parking_spots: 2,
    amenities: ["terraza", "jacuzzi", "vista Ávila", "planta electrica", "agua 24/7", "seguridad", "conserjería"],
    cover_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
    gallery_urls: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
    ],
  }),
  p({
    title: "Llave: Apartamento económico en Catia",
    description: "2 habitaciones, alquiler accesible cerca del metro Plaza Sucre.",
    type: "apartamento",
    address: "Av. Sucre",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.5161,
    lng: -66.9166,
    price_usd: 150,
    deposit_months: 0.5,
    rooms: 2,
    bathrooms: 1,
    area_m2: 60,
    amenities: ["cerca metro", "agua frecuente", "luz frecuente"],
    cover_url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200",
  }),
  p({
    title: "Llave: Casa con piscina en Lechería",
    description: "Casa de playa de 4 habitaciones a 3 cuadras del mar. Piscina propia, parrillera.",
    type: "casa",
    address: "Av. Américo Vespucio",
    city: "Lechería",
    state: "Anzoátegui",
    lat: 10.2078,
    lng: -64.6932,
    price_usd: 700,
    rooms: 4,
    bathrooms: 3,
    area_m2: 240,
    parking_spots: 2,
    amenities: ["piscina", "parrillera", "amoblada", "cerca playa", "aire acondicionado"],
    cover_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
  }),
  p({
    title: "Llave: Habitación amoblada en La Castellana",
    description: "Habitación privada en casa compartida con 2 personas. Baño propio.",
    type: "habitacion",
    address: "Av. Andrés Bello",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.5009,
    lng: -66.8612,
    price_usd: 180,
    deposit_months: 0.5,
    rooms: 1,
    bathrooms: 1,
    area_m2: 18,
    amenities: ["amoblada", "wifi incluido", "servicios incluidos", "baño privado"],
    cover_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
  }),
  p({
    title: "Llave: Apartamento moderno en Barquisimeto",
    description: "3 habitaciones recién remodelado. Zona Este cerca de CCs.",
    type: "apartamento",
    address: "Av. Lara",
    city: "Barquisimeto",
    state: "Lara",
    lat: 10.0639,
    lng: -69.3471,
    price_usd: 300,
    rooms: 3,
    bathrooms: 2,
    area_m2: 110,
    parking_spots: 1,
    amenities: ["remodelado", "seguridad", "agua 24/7", "aire acondicionado"],
    cover_url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200",
  }),
  p({
    title: "Llave: Casa pequeña en Mérida centro",
    description: "Casa de 2 habitaciones con jardín en zona universitaria, ideal estudiantes ULA.",
    type: "casa",
    address: "Av. 2 Lora",
    city: "Mérida",
    state: "Mérida",
    lat: 8.5897,
    lng: -71.1561,
    price_usd: 220,
    rooms: 2,
    bathrooms: 2,
    area_m2: 85,
    parking_spots: 1,
    amenities: ["jardín", "cerca ULA", "agua frecuente", "clima fresco"],
    cover_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
  }),
  p({
    title: "Llave: Local en Centro Comercial Tolón",
    description: "Local de 45m² en piso 2. Ideal boutique o café.",
    type: "local",
    address: "C.C. Tolón, Las Mercedes",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4801,
    lng: -66.8584,
    price_usd: 750,
    deposit_months: 2,
    rooms: 0,
    bathrooms: 0,
    area_m2: 45,
    amenities: ["alto tránsito", "aire central", "seguridad CC", "estacionamiento clientes"],
    cover_url: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1200",
  }),
  p({
    title: "Llave: Apartamento para estrenar en Valencia",
    description: "Apartamento nuevo de 2 habitaciones con acceso biométrico.",
    type: "apartamento",
    address: "Av. Carabobo",
    city: "Valencia",
    state: "Carabobo",
    lat: 10.1685,
    lng: -68.0049,
    price_usd: 260,
    rooms: 2,
    bathrooms: 2,
    area_m2: 75,
    parking_spots: 1,
    amenities: ["nuevo", "acceso biométrico", "cámaras", "planta electrica", "agua 24/7", "gimnasio"],
    cover_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
  }),
  p({
    title: "Llave: Quinta amplia en San Antonio de los Altos",
    description: "5 habitaciones con bosque trasero. Para familias grandes.",
    type: "casa",
    address: "Carretera Panamericana km 18",
    city: "San Antonio",
    state: "Miranda",
    lat: 10.3792,
    lng: -66.9457,
    price_usd: 520,
    rooms: 5,
    bathrooms: 4,
    area_m2: 320,
    parking_spots: 3,
    amenities: ["bosque", "aire fresco", "agua de manantial", "planta electrica", "garage 3 carros"],
    cover_url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
  }),
  p({
    title: "Llave: Studio loft en Las Mercedes",
    description: "Loft moderno de un ambiente para freelancers o estudiantes.",
    type: "apartamento",
    address: "Calle Cali, Las Mercedes",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4799,
    lng: -66.8571,
    price_usd: 240,
    rooms: 1,
    bathrooms: 1,
    area_m2: 50,
    parking_spots: 1,
    amenities: ["moderno", "cocina americana", "luz natural", "wifi fibra"],
    cover_url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200",
  }),
  p({
    title: "Llave: Apartamento familiar en La California",
    description: "3 habitaciones con cuarto de servicio. Edificio tradicional bien mantenido.",
    type: "apartamento",
    address: "Av. Francisco de Miranda",
    city: "Caracas",
    state: "Distrito Capital",
    lat: 10.4929,
    lng: -66.8333,
    price_usd: 320,
    rooms: 3,
    bathrooms: 2,
    area_m2: 120,
    parking_spots: 1,
    amenities: ["cuarto servicio", "conserjería", "planta electrica", "ascensor"],
    cover_url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200",
  }),
];

// In-memory mutable store of demo leads — survives within a single server process.
type DemoLead = {
  id: string;
  property_id: string;
  inquilino_name: string | null;
  inquilino_phone: string | null;
  inquilino_email: string | null;
  status: "nuevo" | "contactado" | "agendado" | "descartado" | "firmado";
  source: "chat" | "directo" | "asesor";
  preferred_visit_at: string | null;
  notes: string | null;
  agent_summary: string | null;
  created_at: string;
};

export const DEMO_LEADS: DemoLead[] = [
  {
    id: crypto.randomUUID(),
    property_id: DEMO_PROPERTIES[0].id,
    inquilino_name: "Carlos González",
    inquilino_phone: "+58 412-9876543",
    inquilino_email: "carlos@example.com",
    status: "agendado",
    source: "chat",
    preferred_visit_at: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    notes: "Pareja joven, busca mudarse en 2 semanas",
    agent_summary: "Inquilino interesado en Las Mercedes. Trabaja en Chacao. Budget $300.",
    created_at: now,
  },
  {
    id: crypto.randomUUID(),
    property_id: DEMO_PROPERTIES[3].id,
    inquilino_name: "Ana López",
    inquilino_phone: "+58 416-5551234",
    inquilino_email: "ana@example.com",
    status: "nuevo",
    source: "chat",
    preferred_visit_at: null,
    notes: null,
    agent_summary: "Médica residente. Busca apto en Maracaibo cerca del hospital.",
    created_at: now,
  },
];
